### ISSUE TITLE
Unable to find template "::datagrid/bootstrap3-paginator.html.twig" in KitpagesDataGridBundle:Grid:bootstrap3-grid.html.twig at line 84.

### ISSUE THREAD

**Issue by b-b3rn4rd** [kitpages/KitpagesDataGridBundle#42]
I am getting the following error when I am trying to use bootstrap3 grid. In my config file I have:
```yml
kitpages_data_grid:
    grid:
        default_twig: KitpagesDataGridBundle:Grid:bootstrap3-grid.html.twig
    paginator:
        default_twig: KitpagesDataGridBundle:Paginator:bootstrap3-paginator.html.twig
```
